syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

option go_package = "solution/exc8/pb";

package models;

// Messages

// todo implement messages

// Represents a single drink item on the menu
message Drink {
  int32 id = 1;
  string name = 2;
  float price = 3;
  string description = 4;
}

// List of all the avilable drinks
message DrinkList {
  repeated Drink drinks = 1;
}

// Represents a signle order (drink type and quantity)
message Order {
  int32 drink_id = 1;
  int32 quantity = 2;
}

// Represents a list of all orders
message Orders {
  repeated Order orders = 1;
}


// Generate go files with:
// Execute `generate_pb.sh`

// Define the gRPC service
service OrderService {
  // todo define rpc functions
  // Returns de list of available drinks
  rpc GetDrinks(google.protobuf.Empty) returns (DrinkList);
  // Places an order for a drink
  rpc OrderDrink(Order) returns (google.protobuf.BoolValue);
  // Returns all placed orders
  rpc GetOrders(google.protobuf.Empty) returns (Orders);
}
